-- Baseline schema for a fresh Supabase project.
--
-- The numbered migrations (0001+) only AMEND an existing database - the
-- original schema was built interactively in the dashboard and never
-- committed. This file is that missing starting point, reconstructed from the
-- live project, so a clone of this repo can stand up its own backend:
--
--   run this file first, then 0001 -> 0007 in order.
--
-- Paste into the Supabase SQL editor (or `supabase db push`). It expects an
-- empty project; IF NOT EXISTS guards make a partial re-run harmless.

-- ── Extensions ──────────────────────────────────────────────────────────────
-- pg_trgm powers the fuzzy name search (the % operator + trigram index).
-- vector (pgvector) stores the CLIP screenshot embeddings.
create extension if not exists pg_trgm with schema public;
create extension if not exists vector with schema extensions;

-- ── games: one row per PlayStation title (metadata from IGDB) ───────────────
-- Loaded by src/desktop_app/load_to_supabase.py from games.parquet.
-- Images are NOT stored here - only IGDB image ids; clients build CDN URLs.
create table if not exists public.games (
  id                      bigint primary key,           -- IGDB game id
  name                    text not null,
  slug                    text unique,
  summary                 text,
  storyline               text,
  release_date            timestamptz,
  release_year            integer,
  rating                  numeric,
  rating_count            integer,
  total_rating            numeric,
  total_rating_count      integer,
  aggregated_rating       numeric,
  aggregated_rating_count integer,
  weighted_score          numeric,
  on_ps4                  boolean not null default false,
  on_ps5                  boolean not null default false,
  cover_id                text,
  screenshot_ids          text[]    not null default '{}',
  artwork_ids             text[]    not null default '{}',
  genres                  text[]    not null default '{}',
  themes                  text[]    not null default '{}',
  game_modes              text[]    not null default '{}',
  player_perspectives     text[]    not null default '{}',
  keywords                text[]    not null default '{}',
  developers              text[]    not null default '{}',
  publishers              text[]    not null default '{}',
  platforms               text[]    not null default '{}',
  platform_ids            integer[] not null default '{}',
  franchises              text[]    not null default '{}',
  collections             text[]    not null default '{}',
  similar_games           bigint[]  not null default '{}',
  num_screenshots         integer,
  hypes                   integer,
  inserted_at             timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create index if not exists games_genres_gin       on public.games using gin (genres);
create index if not exists games_developers_gin   on public.games using gin (developers);
create index if not exists games_publishers_gin   on public.games using gin (publishers);
create index if not exists games_name_trgm        on public.games using gin (name public.gin_trgm_ops);
create index if not exists games_release_year_idx on public.games (release_year);
create index if not exists games_total_rating_idx on public.games (total_rating desc nulls last);

-- ── game_clip_oss: per-screenshot CLIP embeddings, 512-d ────────────────────
-- Built by src/ml/clip_oss/embed.mjs (Xenova/clip-vit-base-patch32, free/CPU)
-- via the "Build CLIP (free / OSS)" workflow. Powers photo search
-- (match_games_by_clip_oss, added in 0006).
create table if not exists public.game_clip_oss (
  id        bigint generated by default as identity primary key,
  game_id   bigint  not null,
  shot_idx  integer not null,
  embedding extensions.vector(512) not null,
  unique (game_id, shot_idx)
);

-- ── game_clip_embeddings: per-screenshot jina-clip-v1 embeddings, 768-d ─────
-- Vectors computed by src/ml/clip_embeddings.py ("Compute CLIP embeddings"
-- workflow). Powers Hidden gems (get_hidden_gems).
create table if not exists public.game_clip_embeddings (
  id        bigint generated by default as identity primary key,
  game_id   bigint  not null references public.games(id) on delete cascade,
  shot_idx  integer not null,
  embedding extensions.vector(768)
);

create index if not exists game_clip_game_idx on public.game_clip_embeddings (game_id);
create index if not exists game_clip_hnsw
  on public.game_clip_embeddings using hnsw (embedding extensions.vector_cosine_ops);

-- ── visual_neighbors: precomputed "Looks alike" lists ───────────────────────
-- Built by src/ml/visual_similarity.py + load_visual_neighbors.py
-- ("Compute visual similarity" workflow). Read by get_visual_recommendations.
create table if not exists public.visual_neighbors (
  game_id      bigint primary key,
  neighbor_ids bigint[] not null,
  scores       real[]   not null,
  model        text,
  updated_at   timestamptz default now()
);

-- ── user_media: player-captured screenshots (links + attribution) ───────────
-- Collected by src/ml/collect_user_media.py ("Collect player media" workflow).
create table if not exists public.user_media (
  id         bigint generated by default as identity primary key,
  game_id    bigint not null,
  source     text   not null check (source in ('steam', 'reddit')),
  image_url  text   not null,
  thumb_url  text,
  author     text,
  source_url text,
  caption    text,
  created_at timestamptz default now(),
  unique (game_id, image_url)
);

create index if not exists user_media_game_idx on public.user_media (game_id);

-- ── Legacy experiment tables ────────────────────────────────────────────────
-- Earlier embedding generations, kept because the optional CI workflows can
-- still write them. Not required by any live app feature.
create table if not exists public.game_clip_v2 (          -- jina-clip-v2
  id        bigint generated by default as identity primary key,
  game_id   bigint  not null,
  shot_idx  integer not null,
  embedding extensions.vector(1024) not null
);

create table if not exists public.game_embeddings (       -- per-game CNN avg
  game_id   bigint primary key references public.games(id) on delete cascade,
  embedding extensions.vector(576)
);

-- ── Row-Level Security: the publishable key may READ, never write ──────────
-- Writes happen only through the service-role key (bypasses RLS), used by the
-- loaders and CI. This is what makes it safe to ship the anon key in the app.
alter table public.games                 enable row level security;
alter table public.game_clip_oss         enable row level security;
alter table public.game_clip_embeddings  enable row level security;
alter table public.visual_neighbors      enable row level security;
alter table public.user_media            enable row level security;
alter table public.game_clip_v2          enable row level security;
alter table public.game_embeddings       enable row level security;

create policy games_public_read           on public.games                for select to anon, authenticated using (true);
create policy "anon read game_clip_oss"   on public.game_clip_oss        for select to anon, authenticated using (true);
create policy "anon read game_clip"       on public.game_clip_embeddings for select to anon, authenticated using (true);
create policy "anon read visual_neighbors" on public.visual_neighbors    for select to anon, authenticated using (true);
create policy "anon read user_media"      on public.user_media           for select to anon, authenticated using (true);
create policy "anon read game_clip_v2"    on public.game_clip_v2         for select to anon using (true);
create policy "anon read game_embeddings" on public.game_embeddings      for select to anon, authenticated using (true);

-- ── Base RPC functions ──────────────────────────────────────────────────────
-- The recommendation functions that later migrations refine:
--   get_recommendations        -> created in 0004, reworked in 0005
--   match_games_by_clip(_oss)  -> created in 0006
-- so only the three functions below need to exist from day one.

-- Type-ahead search: exact prefix first, then fuzzy (trigram) matches.
create or replace function public.search_games(q text, lim integer default 12)
returns table(id bigint, name text, release_year integer, total_rating numeric, cover_id text)
language sql
stable
set search_path to 'public', 'pg_temp'
as $function$
  select g.id, g.name, g.release_year, g.total_rating, g.cover_id
  from public.games g
  where g.name ilike '%' || q || '%' or g.name % q
  order by
    case when lower(g.name) = lower(q) then 0
         when lower(g.name) like lower(q) || '%' then 1
         else 2 end,
    g.release_year desc nulls last,
    g.total_rating desc nulls last
  limit lim;
$function$;

-- "Looks alike": returns the precomputed visual neighbours, in stored order.
create or replace function public.get_visual_recommendations(source_id bigint, lim integer default 12)
returns setof games
language sql
stable
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
  select g.*
  from public.visual_neighbors vn
  cross join lateral unnest(vn.neighbor_ids) with ordinality as n(nid, ord)
  join public.games g on g.id = n.nid
  where vn.game_id = source_id
  order by n.ord
  limit lim;
$function$;

-- "Hidden gems": nearest screenshots in CLIP space (index-accelerated),
-- restricted to titles with fewer than 25 reviews. Same body as 0007.
create or replace function public.get_hidden_gems(source_id bigint, lim integer default 12)
returns setof games
language sql
stable
set search_path to 'public', 'extensions', 'pg_temp'
as $function$
  with src as (
    select avg(embedding) as v
    from public.game_clip_embeddings
    where game_id = source_id
  ),
  cand as (
    select e.game_id, e.embedding <=> (select v from src) as d
    from public.game_clip_embeddings e
    where e.game_id <> source_id
    order by e.embedding <=> (select v from src)
    limit 1000
  ),
  per_game as (
    select game_id, min(d) as d from cand group by game_id
  )
  select g.*
  from public.games g
  join per_game pg on pg.game_id = g.id
  where coalesce(g.total_rating_count, 0) < 25
  order by pg.d
  limit lim;
$function$;
